### PR TITLE
Add accessors for virtual guest network components

### PR DESCRIPTION
**Pull request by sykesm**
- getNetworkComponents
- getPrimaryBackendNetworkComponent
- getPrimaryNetworkComponent

### CODE REVIEW

**Comment by maximilien** [comment]
@sykesm this looks good. One thing is have you thought of adding an integration test?

These are a bit painful but I found that adding integration tests can be quite useful for SL especially since the APIs docs lack docs on how to actually try the calls.

**Comment by sykesm** [comment]
I would have added an integration test if I was able to successfully run what was there. Provided the integration tests on master run, if I ending adding another networking related call (looks like I may need to get a subnet by id) I will back fill.

**Comment by maximilien** [comment]
Let me know which one are failing for you. They should all run though do take some time.

**Comment by sykesm** [comment]
I opened #106 for the integration test issue I hit.

**Pull request merged**
