### PR TITLE
bumping master: TheWeatherCompany changes

### PR DESCRIPTION
**Pull request by maximilien**

### CODE REVIEW

**Comment by maximilien** [comment]
@danielcbright seems that Travis failed. Perhaps not related to your changes...

**Comment by maximilien** [comment]
Seems like `code.google.com/p/go.crypto/ssh` is failing (not sure if permanent). There is a mirror on github: `github.com/golang/go/crypto/ssh` but would need to change import etc.

Let's see if the original location comes online, otherwise, might have to change to github.

/cc @danielcbright @igoonich @markuzet @ebakaev

**Comment by danielcbright** [comment]
> Seems like `code.google.com/p/go.crypto/ssh` is failing (not sure if permanent). There is a mirror here: `github.com/golang/go/crypto/ssh` but would need to change import etc.

>Let's see if the original location comes back online, otherwise, might have to change to github.

@maximilien it looks like go.crypto is [moving to Git per this thread](https://groups.google.com/forum/#!topic/golang-nuts/wPS4H5nkwyU). And from what [the docs](https://godoc.org/golang.org/x/crypto/ssh) say, it looks like the import path is now `import "golang.org/x/crypto/ssh"`. Let me know if you want me to make this change or if you just want to do a quick direct commit to develop to fix it...

**Comment by maximilien** [comment]
Sure if you can get to it before PDT PM when I plan to try. If you submit a PR I will merge to dev and attempt a rebump. Thx.

**Comment by danielcbright** [comment]
@maximilien done https://github.com/maximilien/softlayer-go/pull/87

**Comment by maximilien** [comment]
Closing to recreate to include f7bddf5

**Comment by maximilien** [comment]
Actually, there is a new problem. Travis is failing with:

```
# golang.org/x/crypto/ssh
../../../golang.org/x/crypto/ssh/keys.go:566: undefined: crypto.Signer
```

**Comment by maximilien** [comment]
Leaving this open to allow discussion but trying to see how to fix

**Comment by maximilien** [comment]
OK, seems like from [this post](https://github.com/cloudflare/cfssl/issues/144) that moving to go 1.4.2 (which is what I am using locally) will fix. Updated `.travis.yml`. Let see.

**Comment by maximilien** [comment]
Seems to have worked. OK closing this and will attempt to rebump.

**Pull request closed without merging**
