### PR TITLE
handle response code

### PR DESCRIPTION
**Pull request by cheyang**
This fix can work for issue [https://github.com/maximilien/softlayer-go/issues/93]

### CODE REVIEW

**Comment by maximilien** [comment]
Nice, great catch @cheyang.

Only thing stopping me from merging is that we need to also have some tests. Can you please add to the [unit test here](https://github.com/maximilien/softlayer-go/blob/master/client/softlayer_client_test.go) as a separate `Describe` for HTPP error codes.

I can also add it if you want, but giving you a chance to update your PR first.

Thanks much. Best,

Max

**Comment by cheyang** [comment]
Max, can you help to add the unit test? thanks. :)

**Comment by maximilien** [comment]
Well so I was being nice in saying I'd help... My policy (same as many OSS project) is not to accept PRs that are incomplete. Not having UTs is incomplete IMO. So if I do the UTs then I will test drive it and add the code and not accept your PR.

This is not a lot of code so it's not s problem but keep that in mind for future. Closing this and will fix code and UT soon.

**Comment by cheyang** [comment]
Thanks for training me. :+1:

**Pull request closed without merging**
