### PR TITLE
WIP: allow to specify timeout/interval for waiting for disk ready

### PR DESCRIPTION
**Pull request by mattcui**
@maximilien This PR is for address tracker 127370877, I committed the initial code change, I found there are a dozen SL client requests which need to be faked for the unit test, I hope to let you review the code change before implementing the unit test, it will be a big challenge to me. Thanks.

I had to add 2 packages in Godeps, which caused all packages under Godeps were updated. I think you could update Godeps by yourself and then review the changes in this PR. Please let me know if you want me to submit another PR just for Godeps update. Thanks.

### CODE REVIEW

**Comment by maximilien** [comment]
OK let me update the Godep myself. What packages are those?

I am closing this one.

**Comment by mattcui** [comment]
@maximilien  Please help add the following 2 packages in Godeps:

```
github.com/cloudfoundry/bosh-utils/retrystrategy
github.com/pivotal-golang/clock
```

Thanks.

**Comment by maximilien** [comment]
OK thanks.

**Comment by maximilien** [comment]
OK, done. Try now. If you find there are missing imports then send me what you are doing so I can add imports correctly. Best.

**Pull request closed without merging**
