### PR TITLE
bumping master: TheWeatherCompany changes #86 and f7bddf5 and 55c782e

### PR DESCRIPTION
**Pull request by maximilien**

### CODE REVIEW

**Comment by maximilien** [comment]
OK one more problem... Travis failing with"

```
# github.com/maximilien/softlayer-go/data_types
data_types/softlayer_product_item_price.go:10: Item redeclared in this block
	previous declaration at ../data_types/softlayer_item_price.go:10
data_types/softlayer_product_item_price.go:16: Category redeclared in this block
	previous declaration at ../data_types/softlayer_item_price.go:16
```

Investigating.

**Comment by maximilien** [comment]
Also, you guys need to `go fmt ./...` before submitting PRs. Generally, I think the `bin/test-unit` should have done so for you.

**Comment by maximilien** [comment]
OK, upon inspection, seems that `data_types/softlayer_product_item_price.go` is a duplicate of `data_types/softlayer_item_price.go` trying to remove it and fix.

**Comment by maximilien** [comment]
Guys a lot of things need to be fixed. I removed the `data_types/softlayer_product_item_price.go` and change your code to use `SoftLayer_Product_Item` and when I run tests I started seeing the issue of `uint32` and `int` for IDs, especially in `test_helpers.go`. After fixing that (as a hack) then when I run tests I get this huge mess... can you confirm. Look at my `develop-max` branch. I can help you guys fix things but seems that maybe I am missing something?

See the [errors in this gist](https://gist.github.com/maximilien/bfe921409c3fa38c8386)

**Comment by danielcbright** [comment]
@maximilien I am looking into this now, I will double-check all is working before I commit, I have a hunch where the issue lies.

**Comment by maximilien** [comment]
Yeah, seems all good. Thanks @danielcbright and team.

Merging, finally. Cheers :beers:

**Comment by danielcbright** [comment]
Thanks @maximilien and team, I promise future PR's are going to be a bit more tidy and reasonable in size/scope. Thanks for the patience :)

**Pull request merged**
