### PR TITLE
Adding remaining Virtual Guest CRUD operations

### PR DESCRIPTION
**Pull request by danielcbright**
In reference to the work we've been doing to complete the Terraform SoftLayer Provider work that @eirslett started. We've been working on getting all CRUD operations for Virtual Guests implemented as referenced here https://github.com/TheWeatherCompany/softlayer-go/issues/4 and here https://github.com/TheWeatherCompany/terraform/issues/5. This PR includes quite a few additions that fully round out Virtual Guest abilities.

### CODE REVIEW

**Comment by danielcbright** [comment]
Looks like an issue with github.com/tools/godep

**Comment by maximilien** [comment]
Nice. Can you please update so Travis passes? It might be you need to rebase since I've made some changes yesterday. Once you do and resubmit I will review ASAP. Thanks,
Max

**Comment by maximilien** [comment]
OK seems that `github,com/tools/godep` was down or something so that caused the failure. I restarted job and all good.

Let me review. Thanks.

**Comment by maximilien** [comment]
Hi, all,

Thanks for your contributions, however, I am not able to merge it because you have no tests!

As you can see we have unit tests for every public methods for any class we have. Additionally, I would feel more comfortable if you also added a new integration test that exercises the new methods. If does not have to be thorough but should at least exercise the main new features.

I am closing this PR and hope you can make the additions I suggest and resubmit. I will then review again.

Thanks and look forward to your updated PR.

Best,

dr.max

**Comment by danielcbright** [comment]
@igoonich let's get those tests written and resubmit this ASAP.

Thanks!

**Comment by danielcbright** [comment]
@maximilien thanks for the feedback, you have a great project here and I'm glad we can contribute!

**Pull request closed without merging**
