### PR TITLE
Retry when timeout error returned from http client

### PR DESCRIPTION
**Pull request by mattcui**
@maximilien I followed [gomega ghttp approach](https://onsi.github.io/gomega/#ghttp-testing-http-clients) to write the unit test. It's running a real http server, so it's also pretty like integration test when sending requests from the http client. I had to update Godeps to update gomega and added  ghttp. Please help review. Thanks.

### CODE REVIEW

**Comment by maximilien** [comment]
Nice @mattcui. Let me review. Thx

**Comment by maximilien** [comment]
Hey I wonder if we should make the default retry 1. That way all current users would not have the side effects of retry. If they need it then they should set the env, like in your case.

Also, I feel you should have more tests. Specifically, I am thinking of tests that cause failures during retry and then succeeds and overall succeeds the test. So something like with 5 retry:

1. fails
2. fails
3. succeeds

All good. And:

1. fails
2. fails
3. fails
4. fails
5. succeed

all good. So essentially verifying that all cases (first try, middle try, and last try work).  

Finally, you should also have tests that verify that the retry count value and wait value are set with env variable. So if you set env before that the new retry count is updated.

Do these and I will merge. Looking better. Thx.

**Comment by mattcui** [comment]
@maximilien I think I already addressed your comments:

1. Set the default value of retry count to 1.
2. Used go routine to start the test HTTP server with several seconds delay, so the http client can't access the server at the beginning of several tryouts, and then it can finally.
3. The test code updated those 2 environment variables.

It's ready for review. Thanks.

**Comment by maximilien** [comment]
Cool. Thanks 👍

**Pull request merged**
